"""empty message

Revision ID: 11925c05c683
Revises: c3d7fa5b2986
Create Date: 2020-10-02 19:44:52.077419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11925c05c683'
down_revision = 'c3d7fa5b2986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
