"""empty message

Revision ID: 2733acbf66a4
Revises: e229a7d55073
Create Date: 2020-10-03 20:23:56.570614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2733acbf66a4'
down_revision = 'e229a7d55073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_ibfk_2', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'user', ['requester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_ibfk_2', 'documents', 'user', ['requester'], ['username'])
    # ### end Alembic commands ###
