"""empty message

Revision ID: 28f6a5003341
Revises: 65babc6ab4a1
Create Date: 2020-10-03 21:02:15.231140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f6a5003341'
down_revision = '65babc6ab4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'cargo', ['cargo'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'cargo', ['cargo'], ['id'])
    # ### end Alembic commands ###
