"""empty message

Revision ID: 34d46fd4354b
Revises: 030bc6e72c9c
Create Date: 2021-07-06 10:22:16.860467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d46fd4354b'
down_revision = '030bc6e72c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_ibfk_1', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'types_reg', ['type'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_ibfk_1', 'documents', 'types_reg', ['type'], ['id'])
    # ### end Alembic commands ###
