"""empty message

Revision ID: 642b4c2ee8a1
Revises: 28f6a5003341
Create Date: 2020-10-03 21:03:39.926135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642b4c2ee8a1'
down_revision = '28f6a5003341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'cargo', ['cargo'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
