"""empty message

Revision ID: 65babc6ab4a1
Revises: 66940d2518d0
Create Date: 2020-10-03 20:39:19.469839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65babc6ab4a1'
down_revision = '66940d2518d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents', 'user', ['requester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # ### end Alembic commands ###
