"""empty message

Revision ID: 77813524fea3
Revises: 92ea83fa3665
Create Date: 2020-10-01 13:09:25.660386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77813524fea3'
down_revision = '92ea83fa3665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_reg', sa.String(length=9), nullable=False),
    sa.Column('objeto', sa.String(length=60), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('destiny', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=6), nullable=False),
    sa.Column('requester', sa.String(length=20), nullable=False),
    sa.Column('creator', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_reg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
