"""empty message

Revision ID: 9be5ac0b3aaf
Revises: 399fde4644d0
Create Date: 2020-10-03 17:06:54.163753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be5ac0b3aaf'
down_revision = '399fde4644d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('type_reg', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'documents', ['type_reg'])
    op.create_foreign_key(None, 'documents', 'types_reg', ['type_reg'], ['id'])
    op.create_foreign_key(None, 'documents', 'user', ['requester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'type_reg')
    # ### end Alembic commands ###
