"""empty message

Revision ID: bf962dbff76f
Revises: 195ef9e0c1d4
Create Date: 2020-10-19 10:00:53.715886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf962dbff76f'
down_revision = '195ef9e0c1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=260),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=260),
               nullable=True)
    # ### end Alembic commands ###
