"""empty message

Revision ID: cc02fcf4f0eb
Revises: 9be5ac0b3aaf
Create Date: 2020-10-03 19:02:57.184630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc02fcf4f0eb'
down_revision = '9be5ac0b3aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents', 'user', ['requester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # ### end Alembic commands ###
