"""empty message

Revision ID: e024d4e70e47
Revises: 0e40cb4d33d6
Create Date: 2020-10-03 19:25:28.297860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e024d4e70e47'
down_revision = '0e40cb4d33d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'types_reg', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'type')
    # ### end Alembic commands ###
