"""empty message

Revision ID: fca245d13593
Revises: bf962dbff76f
Create Date: 2020-11-01 11:36:01.530551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca245d13593'
down_revision = 'bf962dbff76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('tipo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'tipo')
    # ### end Alembic commands ###
